import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'

// HTTPS certs for LAN mic access (generated by mkcert)
const certDir = path.resolve(__dirname, '..')
const https = fs.existsSync(path.join(certDir, '192.168.1.104+2.pem'))
  ? {
      key: fs.readFileSync(path.join(certDir, '192.168.1.104+2-key.pem')),
      cert: fs.readFileSync(path.join(certDir, '192.168.1.104+2.pem')),
    }
  : undefined

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5174,
    https,
    proxy: {
      '/api': 'http://127.0.0.1:8001',
      '/data': 'http://127.0.0.1:8001',
    },
  },
})
